Document: canaima-control-parental
Title: Debian canaima-control-parental Manual
Author: <insert document author here>
Abstract: This manual describes what canaima-control-parental is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/canaima-control-parental/canaima-control-parental.sgml.gz

Format: postscript
Files: /usr/share/doc/canaima-control-parental/canaima-control-parental.ps.gz

Format: text
Files: /usr/share/doc/canaima-control-parental/canaima-control-parental.text.gz

Format: HTML
Index: /usr/share/doc/canaima-control-parental/html/index.html
Files: /usr/share/doc/canaima-control-parental/html/*.html
