#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-control-parental
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2011 Carlos Escobar <carlosescobar70@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-control-parental"

case ${1} in

	configure)

        # Aquí va lo que el paquete debe configurar/crear/borrar después de
        # instalarse. Lenguaje a usar: BASH.

	cat /usr/share/canaima-control-parental/dansguardian/dansguardianf.conf > /etc/dansguardian/dansguardianf.conf
	cat /usr/share/canaima-control-parental/dansguardian/dansguardianf1.conf > /etc/dansguardian/dansguardianf1.conf
	cat /usr/share/canaima-control-parental/dansguardian/dansguardian > /etc/init.d/dansguardian
	cat /usr/share/canaima-control-parental/tinyproxy.conf > /etc/dansguardian/tinyproxy.conf
	#Una vez copiadas las configuraciones iniciamos los procesos:
	invoke-rc.d tinyproxy start
	invoke-rc.d dansguardian start 

	;;

        abort-upgrade|abort-remove|abort-deconfigure)

        # Aquí va lo que el paquete debe configurar/crear/borrar en caso
        # de abortarse la instalación. Lenguaje a usar: BASH.

        ;;

        *)

                echo "postinst no reconoce el argumento '"${1}"'" >&2
                exit 1

        ;;

esac

#DEBHELPER#

exit 0
